// Time
export const UPDATE_TIME = 'UPDATE_TIME';

// Auth
export const USER_LOGIN_REQUEST                   = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS                   = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR                     = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_SUCCESS                  = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FROM_ALL_DEVICES_SUCCESS = 'USER_LOGOUT_FROM_ALL_DEVICES_SUCCESS';
export const USER_LOGOUT_FROM_ALL_DEVICES_ERROR   = 'USER_LOGOUT_FROM_ALL_DEVICES_ERROR';

export const USER_TOKEN_REFRESH_SUCCESS           = 'USER_TOKEN_REFRESH_SUCCESS';
export const USER_TOKEN_REFRESH_FAILURE           = 'USER_TOKEN_REFRESH_FAILURE';

// Account
export const GET_ACCOUNT_DATA_REQUEST = 'GET_ACCOUNT_DATA_REQUEST';
export const GET_ACCOUNT_DATA_SUCCESS = 'GET_ACCOUNT_DATA_SUCCESS';
export const GET_ACCOUNT_DATA_ERROR   = 'GET_ACCOUNT_DATA_ERROR';
export const SET_ACCOUNT_DATA_SUCCESS = 'SET_ACCOUNT_DATA_SUCCESS';
export const SET_ACCOUNT_DATA_ERROR   = 'SET_ACCOUNT_DATA_ERROR';

// Bonuses
export const FETCH_FILL_INFO_BONUS_SUCCESS = 'FETCH_FILL_INFO_BONUS_SUCCESS';
export const FETCH_FILL_INFO_BONUS_FAILURE = 'FETCH_FILL_INFO_BONUS_FAILURE';

// Modals
export const SHOW_MODAL     = 'SHOW_MODAL';
export const HIDE_MODAL     = 'HIDE_MODAL';
export const REDIRECT_MODAL = 'REDIRECT_MODAL';

// Profit
export const GET_PROFIT_DATA_REQUEST = 'GET_PROFIT_DATA_REQUEST';
export const GET_PROFIT_DATA_SUCCESS = 'GET_PROFIT_DATA_SUCCESS';
export const GET_PROFIT_DATA_ERROR   = 'GET_PROFIT_DATA_ERROR';

// Wallet
export const GET_USER_WALLET_DATA_REQUEST      = 'GET_USER_WALLET_DATA_REQUEST';
export const GET_USER_WALLET_DATA_SUCCESS      = 'GET_USER_WALLET_DATA_SUCCESS';
export const GET_USER_WALLET_DATA_ERROR        = 'GET_USER_WALLET_DATA_ERROR';
export const SET_WALLET_ACTIVE_BALANCE_SUCCESS = 'SET_WALLET_ACTIVE_BALANCE_SUCCESS';
export const SET_WALLET_ACTIVE_BALANCE_ERROR   = 'SET_WALLET_ACTIVE_BALANCE_ERROR';
export const UPDATE_WALLET_BALANCE             = 'UPDATE_WALLET_BALANCE';

// Assets
export const GET_ASSETS_DATA_REQUEST = 'GET_ASSETS_DATA_REQUEST';
export const GET_ASSETS_DATA_SUCCESS = 'GET_ASSETS_DATA_SUCCESS';
export const GET_ASSETS_DATA_ERROR   = 'GET_ASSETS_DATA_ERROR';

// Sidebar
export const SWITCH_SIDEBAR                   = 'SWITCH_SIDEBAR';

export const REQUEST_SIDEBAR_DATA             = 'REQUEST_SIDEBAR_DATA';

export const FETCH_NEWS_DATA_REQUEST          = 'FETCH_NEWS_DATA_REQUEST';
export const FETCH_NEWS_DATA_SUCCESS          = 'FETCH_NEWS_DATA_SUCCESS';
export const FETCH_NEWS_DATA_FAILURE          = 'FETCH_NEWS_DATA_FAILURE';

// Websockets
export const RECEIVE_WS_TOKEN_SUCCESS = 'RECEIVE_WS_TOKEN_SUCCESS';
export const RECEIVE_WS_TOKEN_ERROR   = 'RECEIVE_WS_TOKEN_ERROR';
export const CONNECT_TO_WS            = 'CONNECT_TO_WS';
export const DISCONNECT_FROM_WS       = 'DISCONNECT_FROM_WS';
export const ON_WS_OPEN               = 'ON_WS_OPEN';
export const ON_WS_CLOSE              = 'ON_WS_CLOSE';
export const ON_WS_ERROR              = 'ON_WS_ERROR';
export const ON_WS_MESSAGE            = 'ON_WS_MESSAGE';
export const UPDATE_WS_SET_SUCCESS    = 'UPDATE_WS_SET_SUCCESS';
export const UPDATE_WS_SET_ERROR      = 'UPDATE_WS_SET_ERROR';

// Common action types for groups/charts/trades/countdowns
export const ADD_CHARTS    = 'ADD_CHARTS';
export const REMOVE_CHARTS = 'REMOVE_CHARTS';

// Chart
export const REMOVE_COUNTDOWN                   = 'REMOVE_COUNTDOWN';
export const UPDATE_CHART_DATA                  = 'UPDATE_CHART_DATA';
export const UPDATE_CHART_HISTORY_DATA          = 'UPDATE_CHART_HISTORY_DATA';

export const REQUEST_CHART_HISTORY_DATA         = 'REQUEST_CHART_HISTORY_DATA';
export const RECEIVE_CHART_HISTORY_DATA_SUCCESS = 'RECEIVE_CHART_HISTORY_DATA_SUCCESS';
export const RECEIVE_CHART_HISTORY_DATA_ERROR   = 'RECEIVE_CHART_HISTORY_DATA_ERROR';

export const CHANGE_CHART_INTERVAL              = 'CHANGE_CHART_INTERVAL';
export const CHANGE_CHART_TYPE                  = 'CHANGE_CHART_TYPE';

export const TOGGLE_MOOD_INDICATOR              = 'TOGGLE_MOOD_INDICATOR';
export const TOGGLE_NEWS                        = 'TOGGLE_NEWS';
export const TOGGLE_TOOLS                       = 'TOGGLE_TOOLS';

export const SET_TIMEVIEW_STATE                 = 'SET_TIMEVIEW_STATE';

export const SHOW_TRADE_GRADIENT                = 'SHOW_TRADE_GRADIENT';
export const HIDE_TRADE_GRADIENT                = 'HIDE_TRADE_GRADIENT';

export const FETCH_CHART_EVENTS_DATA_REQUEST    = 'FETCH_CHART_EVENTS_DATA_REQUEST';
export const FETCH_CHART_EVENTS_DATA_SUCCESS    = 'FETCH_CHART_EVENTS_DATA_SUCCESS';
export const FETCH_CHART_EVENTS_DATA_FAILURE    = 'FETCH_CHART_EVENTS_DATA_FAILURE';

// Trade
export const SET_TRADE_AMOUNT    = 'SET_TRADE_AMOUNT';
export const SET_TRADE_TIME      = 'SET_TRADE_TIME';
export const SET_COUNTDOWN_TIMER = 'SET_COUNTDOWN_TIMER';

// Bets
export const ADD_BET_FRONTEND_SUCCESS    = 'ADD_BET_FRONTEND_SUCCESS';
export const ADD_BET_FRONTEND_FAILURE    = 'ADD_BET_FRONTEND_FAILURE';
export const ADD_BET_BACKEND_SUCCESS     = 'ADD_BET_BACKEND_SUCCESS';
export const ADD_BET_BACKEND_FAILURE     = 'ADD_BET_BACKEND_FAILURE';

export const CLOSE_BET_FRONTEND_SUCCESS  = 'CLOSE_BET_FRONTEND_SUCCESS';
export const CLOSE_BET_FRONTEND_FAILURE  = 'CLOSE_BET_FRONTEND_FAILURE';

export const CHECK_BETS_FRONTEND_SUCCESS = 'CHECK_BETS_FRONTEND_SUCCESS';
export const CHECK_BETS_FRONTEND_FAILURE = 'CHECK_BETS_FRONTEND_FAILURE';
export const CHECK_BETS_BACKEND_SUCCESS  = 'CHECK_BETS_BACKEND_SUCCESS';
export const CHECK_BETS_BACKEND_FAILURE  = 'CHECK_BETS_BACKEND_FAILURE';

export const FETCH_BETS_REQUEST          = 'FETCH_BETS_REQUEST';
export const FETCH_BETS_SUCCESS          = 'FETCH_BETS_SUCCESS';
export const FETCH_BETS_FAILURE          = 'FETCH_BETS_FAILURE';
